// Generated by scripts/write-pe-exam-source-status.mjs.
// Do not edit manually; run npm.cmd run pe-exam:data:status after source snapshots change.
export const peExamSourceStatusSnapshot = {
  "statusVersion": 1,
  "generatedBy": "scripts/write-pe-exam-source-status.mjs",
  "sourceSnapshotsMaxGeneratedAt": "2026-06-27T11:51:47.196Z",
  "defaults": {
    "maxAgeDays": 120
  },
  "sources": [
    {
      "key": "kusfEarlySummary",
      "label": "KUSF early admission summary",
      "file": "app/pe-exam/kusfAdmissionData.ts",
      "exportName": "kusfAdmissionSnapshot",
      "sourceName": "KUSF 체육특기자대입포털 체육관련학과 대입전형",
      "sourceUrl": "https://info.kusf.or.kr/kusf/portal/bbs/kusfeipetcselctninf/selectEntEtcSelctnList.do",
      "schoolYear": "2026",
      "resultYear": "",
      "generatedAt": "2026-06-26T15:21:48.463Z",
      "universityCount": 207,
      "admissionCount": 1045,
      "minSchoolYearOffset": 0,
      "minResultYearOffset": null,
      "minUniversities": 180,
      "minAdmissions": 800
    },
    {
      "key": "kusfEarlyDetail",
      "label": "KUSF early admission detail",
      "file": "app/pe-exam/kusfAdmissionDetailData.ts",
      "exportName": "kusfAdmissionDetailSnapshot",
      "sourceName": "KUSF 체육관련학과 대입전형 상세",
      "sourceUrl": "https://info.kusf.or.kr/kusf/portal/bbs/kusfeipetcselctninf/selectEntEtcSelctnList.do",
      "schoolYear": "2026",
      "resultYear": "",
      "generatedAt": "2026-06-26T16:17:21.215Z",
      "universityCount": 206,
      "admissionCount": 1045,
      "minSchoolYearOffset": 0,
      "minResultYearOffset": null,
      "minUniversities": 0,
      "minAdmissions": 800
    },
    {
      "key": "adigaRegularAdmission",
      "label": "ADIGA regular admission",
      "file": "app/pe-exam/adigaRegularAdmissionData.ts",
      "exportName": "adigaRegularAdmissionSnapshot",
      "sourceName": "대입정보포털 어디가 대학 모집인원",
      "sourceUrl": "https://www.adiga.kr/ucp/uvt/uni/univView.do?menuId=PCUVTINF2000",
      "schoolYear": "2027",
      "resultYear": "",
      "generatedAt": "2026-06-26T15:47:08.984Z",
      "universityCount": 207,
      "admissionCount": 155,
      "minSchoolYearOffset": 1,
      "minResultYearOffset": null,
      "minUniversities": 180,
      "minAdmissions": 100
    },
    {
      "key": "adigaRegularSelection",
      "label": "ADIGA regular result",
      "file": "app/pe-exam/adigaRegularSelectionData.ts",
      "exportName": "adigaRegularSelectionSnapshot",
      "sourceName": "대입정보포털 어디가 평가기준·입시결과",
      "sourceUrl": "https://www.adiga.kr/ucp/uvt/uni/univView.do?menuId=PCUVTINF2000",
      "schoolYear": "2027",
      "resultYear": "2026",
      "generatedAt": "2026-06-27T11:51:47.196Z",
      "universityCount": 89,
      "admissionCount": 319,
      "minSchoolYearOffset": 1,
      "minResultYearOffset": 0,
      "minUniversities": 60,
      "minAdmissions": 200
    }
  ]
};
