import type { AppState } from "./types";
import { PROTOTYPE_REFERENCE_DATE, rebaseAppStateDates } from "./appDates";

export const defaultAppState: AppState = {
  studentName: "김도윤",
  scheduleDate: PROTOTYPE_REFERENCE_DATE,
  guardianPermissions: {
    attendance: false,
    contract: false,
    academics: false,
    practical: false,
  },
  tasks: [
    {
      id: "task-study-english",
      title: "영어 독해 2지문",
      detail: "완벽하게 풀기보다 오답 이유 한 줄만 남기기",
      kind: "study",
      scheduledDate: "2026-08-02",
      scheduledTime: "16:30",
      durationMinutes: 35,
      completed: false,
      assignedBy: "student",
    },
    {
      id: "task-training-jump",
      title: "제멀 리듬 훈련",
      detail: "5회 3세트 · 무릎 불편 시 바로 중단",
      kind: "training",
      scheduledDate: "2026-08-02",
      scheduledTime: "19:00",
      durationMinutes: 50,
      completed: false,
      assignedBy: "coach",
    },
    {
      id: "task-recovery",
      title: "하체 회복 루틴",
      detail: "호흡과 가벼운 가동성 12분",
      kind: "recovery",
      scheduledDate: "2026-08-02",
      scheduledTime: "21:20",
      durationMinutes: 12,
      completed: false,
      assignedBy: "coach",
    },
    {
      id: "task-week-math",
      title: "수학 오답 노트 정리",
      detail: "틀린 이유와 다음 풀이 순서를 한 줄씩 남기기",
      kind: "study",
      scheduledDate: "2026-08-03",
      scheduledTime: "18:00",
      durationMinutes: 50,
      completed: false,
      assignedBy: "student",
    },
    {
      id: "task-week-shuttle",
      title: "왕복달리기 페이스 훈련",
      detail: "후반 2회 속도가 무너지지 않도록 구간 기록 확인",
      kind: "training",
      scheduledDate: "2026-08-04",
      scheduledTime: "19:10",
      durationMinutes: 45,
      completed: false,
      assignedBy: "coach",
    },
    {
      id: "task-week-recovery",
      title: "취침 전 회복 루틴",
      detail: "하체 이완과 수면 준비 호흡",
      kind: "recovery",
      scheduledDate: "2026-08-05",
      scheduledTime: "22:00",
      durationMinutes: 15,
      completed: false,
      assignedBy: "student",
    },
  ],
  studySessions: [],
  recordItems: [
    {
      id: "record-item-study-focus",
      category: "study",
      name: "집중 공부",
      suggestedUnit: "분",
      createdBy: "system",
      active: true,
      pbDirection: "higher",
    },
    {
      id: "record-item-study-score",
      category: "study",
      name: "모의고사 점수",
      suggestedUnit: "점",
      createdBy: "system",
      active: true,
      pbDirection: "higher",
    },
    {
      id: "record-item-training-jump",
      category: "training",
      name: "제자리멀리뛰기",
      suggestedUnit: "cm",
      createdBy: "system",
      active: true,
      pbDirection: "higher",
    },
    {
      id: "record-item-training-shuttle",
      category: "training",
      name: "10m 왕복달리기",
      suggestedUnit: "초",
      createdBy: "system",
      active: true,
      pbDirection: "lower",
    },
    {
      id: "record-item-condition-energy",
      category: "condition",
      name: "에너지",
      suggestedUnit: "/5",
      createdBy: "system",
      active: true,
      pbDirection: "higher",
    },
    {
      id: "record-item-condition-focus",
      category: "condition",
      name: "집중 가능",
      suggestedUnit: "/5",
      createdBy: "system",
      active: true,
      pbDirection: "higher",
    },
    {
      id: "record-item-condition-soreness",
      category: "condition",
      name: "몸의 뻐근함",
      suggestedUnit: "/5",
      createdBy: "system",
      active: true,
      pbDirection: "lower",
    },
    {
      id: "record-item-condition-sleep",
      category: "condition",
      name: "수면 시간",
      suggestedUnit: "시간",
      createdBy: "system",
      active: true,
      pbDirection: "higher",
    },
  ],
  studentRecords: [
    {
      id: "record-training-jump-1",
      itemId: "record-item-training-jump",
      category: "training",
      value: "268",
      unit: "cm",
      note: "착지 균형을 함께 확인한 기록",
      recordedAt: "2026-08-01T19:35:00+09:00",
      source: "coach",
      validationStatus: "valid",
    },
    {
      id: "record-training-shuttle-1",
      itemId: "record-item-training-shuttle",
      category: "training",
      value: "8.72",
      unit: "초",
      note: "실내 10m 구간 기준",
      recordedAt: "2026-08-01T19:50:00+09:00",
      source: "coach",
      validationStatus: "valid",
    },
  ],
  calendarEvents: [
    {
      id: "event-training",
      title: "체대입시 실기 수업",
      startsAt: "2026-08-01T19:00:00+09:00",
      endsAt: "2026-08-01T20:20:00+09:00",
      category: "training",
      source: "coach",
      note: "제멀·10m 왕복달리기",
    },
    {
      id: "event-mock-exam",
      title: "8월 모의평가",
      startsAt: "2026-08-05T08:30:00+09:00",
      endsAt: "2026-08-05T16:30:00+09:00",
      category: "exam",
      source: "manual",
    },
  ],
  condition: {
    energy: 3,
    focus: 3,
    soreness: 2,
    checkedAt: null,
  },
  guardianMessages: [
    {
      id: "message-coach-1",
      body: "이번 주 훈련 일정 문의가 있으면 이곳에 남겨주세요.",
      sentAt: "2026-08-01T09:00:00+09:00",
      status: "received",
    },
  ],
  coachConversation: [
    {
      id: "coach-conversation-1",
      sender: "coach",
      body: "도윤 학생, 오늘 제자리멀리뛰기는 기록보다 착지 균형을 먼저 확인하겠습니다.",
      sentAt: "2026-08-01T10:10:00+09:00",
      aiAssisted: false,
      attachments: [],
    },
    {
      id: "coach-conversation-2",
      sender: "student",
      body: "네, 오른쪽 무릎이 조금 뻐근한데 워밍업 후 상태도 같이 말씀드릴게요.",
      sentAt: "2026-08-01T10:14:00+09:00",
      aiAssisted: false,
      attachments: [],
    },
  ],
  assistantConversation: [
    {
      id: "assistant-welcome",
      sender: "assistant",
      body: "안녕하세요! 일정 등록이나 코치 상담이 필요하면 편하게 말씀해주세요. 예: \"내일 오후 6시 실기 훈련 등록해줘\"",
      sentAt: "2026-08-01T09:00:00+09:00",
    },
  ],
};

export function createDefaultAppStateForDate(dateKey: string) {
  return rebaseAppStateDates(defaultAppState, PROTOTYPE_REFERENCE_DATE, dateKey);
}

export function createEmptyAppStateForDate(dateKey: string): AppState {
  const base = createDefaultAppStateForDate(dateKey);

  return {
    ...base,
    guardianPermissions: {
      attendance: false,
      contract: false,
      academics: false,
      practical: false,
    },
    tasks: [],
    studySessions: [],
    recordItems: base.recordItems
      .filter((item) => item.createdBy === "system")
      .map((item) => ({ ...item })),
    studentRecords: [],
    calendarEvents: [],
    condition: {
      energy: 3,
      focus: 3,
      soreness: 2,
      checkedAt: null,
    },
    guardianMessages: [],
    coachConversation: [],
    assistantConversation: [],
  };
}
