import Image from "next/image";
import Link from "next/link";
function Header(){return <header className="site-header"><div className="container header-inner"><Link href="/" className="logo-link"><Image src="/images/reperformance-logo.png" alt="RePERFORMANCE" width={360} height={100} className="logo-img"/></Link><nav className="nav"><Link href="/services">서비스</Link><Link href="/system">시스템</Link><Link href="/coach">코치</Link><Link href="/location">위치</Link><Link href="/contact" className="nav-cta">상담</Link></nav></div></header>}
function Footer(){return <footer className="footer"><div className="container footer-inner"><p>© RePERFORMANCE. All rights reserved.</p><p>전북 전주시 완산구 서신동 773-2, 2층 · 010-2418-8400</p></div></footer>}
export default function LocationPage(){return <main><Header />
<section className="page-hero"><div className="container page-title"><p className="eyebrow">LOCATION</p><h1>전주 서신동 RePERFORMANCE</h1><p>전북 전주시 완산구 서신동 773-2, 2층. 서신신협 2층에 위치해 있으며, 건물 뒷편 주차가 가능합니다.</p></div></section>
<section className="section"><div className="container grid-2"><div className="contact-box"><h2>오시는 길</h2><div className="contact-list"><div><strong>주소</strong><span>전북 전주시 완산구 서신동 773-2, 2층</span></div><div><strong>위치 안내</strong><span>서신신협 2층</span></div><div><strong>주차</strong><span>건물 뒷편 주차 가능</span></div><div><strong>운영 시간</strong><span>08:00 ~ 22:00</span></div></div></div><div className="contact-box"><h2>연락처</h2><div className="contact-list"><div><strong>전화</strong><span>010-2418-8400</span></div><div><strong>Instagram</strong><span>@reperformance_trainer</span></div></div><div className="button-row"><a href="tel:010-2418-8400" className="button primary">전화하기</a><a href="https://www.instagram.com/reperformance_trainer" target="_blank" rel="noopener noreferrer" className="button secondary">인스타그램</a></div></div></div></section>
<section className="section light"><div className="container"><div className="notice">지도 또는 네이버 플레이스 링크가 준비되면 이 영역에 바로 삽입할 수 있습니다.</div></div></section>
<Footer /></main>}
